drop table if exists term;
drop table if exists vocabulary;
drop table if exists user_info;
drop table if exists social_user;
drop table if exists users;
drop table if exists template_term;
drop table if exists template_vocabulary;
drop table if exists demo_term_synonym;
drop table if exists demo_term;
